/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

//import static com.sun.javafx.scene.CameraHelper.project;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    public Okno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stranaA = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        stranaB = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        stranaC = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        uhelA = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        uhelB = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        uhelC = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vyberUhlu = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        sinus = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        cosinus = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        tangen = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        obvod = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        obsah = new javax.swing.JTextPane();
        Vypocti = new javax.swing.JButton();
        dopocti = new javax.swing.JButton();
        dopocti_strany = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Strana a:");

        jLabel2.setText("Strana b:");

        jLabel3.setText("Strana c:");

        stranaA.setText("0");
        jScrollPane1.setViewportView(stranaA);

        stranaB.setText("0");
        jScrollPane2.setViewportView(stranaB);

        stranaC.setText("0");
        jScrollPane3.setViewportView(stranaC);

        jLabel4.setText("Úhel  a:");

        jLabel5.setText("Úhel b:");

        jLabel6.setText("Úhel c:");

        uhelA.setText("0");
        jScrollPane4.setViewportView(uhelA);

        uhelB.setText("0");
        jScrollPane5.setViewportView(uhelB);

        uhelC.setText("0");
        jScrollPane6.setViewportView(uhelC);

        jLabel7.setText("Obvod:");

        jLabel8.setText("Obsah:");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/8.png"))); // NOI18N
        jLabel9.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel9AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        vyberUhlu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "úhel a", "úhel b", "úhel c" }));
        vyberUhlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vyberUhluActionPerformed(evt);
            }
        });

        jLabel10.setText("Vyber Úhel");

        jLabel11.setText("Sin");

        jLabel12.setText("Cos");

        jLabel13.setText("Tan");

        sinus.setText("0");
        jScrollPane7.setViewportView(sinus);

        cosinus.setText("0");
        jScrollPane8.setViewportView(cosinus);

        tangen.setText("0");
        jScrollPane9.setViewportView(tangen);

        obvod.setText("0");
        jScrollPane10.setViewportView(obvod);

        obsah.setText("0");
        jScrollPane11.setViewportView(obsah);

        Vypocti.setText("Vypočti");
        Vypocti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VypoctiActionPerformed(evt);
            }
        });

        dopocti.setText("Dopočítat");
        dopocti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dopoctiActionPerformed(evt);
            }
        });

        dopocti_strany.setText("Dopočítat");
        dopocti_strany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dopocti_stranyActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Trojúhelník");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(jScrollPane11)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(Vypocti)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(vyberUhlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane8))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reset)))
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(dopocti))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(dopocti_strany)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vyberUhlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dopocti_strany))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dopocti))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane9)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vypocti)
                            .addComponent(reset))
                        .addGap(19, 19, 19))))
        );

        pack();
    }// </editor-fold>                        

    private void vyberUhluActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
        switch(vyberUhlu.getSelectedIndex()){
            case 0:
                if(Float.parseFloat(uhelA.getText())==90){
                    String alfasin = "1.0";
                    String alfacos = "0.0";
                    String alfatan = "NaN";
                    cosinus.setText(alfacos);
                    tangen.setText(alfatan);
                    sinus.setText(alfasin);
                }else{
                    String alfasin = Float.toString((float) Math.sin(Float.parseFloat(uhelA.getText())/ (180 / Math.PI)));
                    String alfacos = Float.toString((float) Math.cos(Float.parseFloat(uhelA.getText())/ (180 / Math.PI)));
                    String alfatan = Float.toString((float) Math.tan(Float.parseFloat(uhelA.getText())/ (180 / Math.PI)));
                    cosinus.setText(alfacos);
                    tangen.setText(alfatan);
                    sinus.setText(alfasin);
                }
                if(Float.parseFloat(uhelA.getText())==30){
                    String alfasin = "0.5";
                    String alfacos = "√3/2";
                    String alfatan = "√3/3";
                    cosinus.setText(alfacos);
                    tangen.setText(alfatan);
                    sinus.setText(alfasin);
                }
                if(Float.parseFloat(uhelA.getText())==45){
                    String alfasin = "√2/2";
                    String alfacos = "√2/2";
                    String alfatan = "1.0";
                    cosinus.setText(alfacos);
                    tangen.setText(alfatan);
                    sinus.setText(alfasin);
                }
                if(Float.parseFloat(uhelA.getText())==60){
                    String alfasin = "√3/2";
                    String alfacos = "0.5";
                    String alfatan = "√3";
                    cosinus.setText(alfacos);
                    tangen.setText(alfatan);
                    sinus.setText(alfasin);
                }
                        
                break;
            case 1:
                if(Float.parseFloat(uhelB.getText())==90){
                    String betasin = "1.0";
                    String betacos = "0.0";
                    String betatan = "NaN";
                    cosinus.setText(betacos);
                    tangen.setText(betatan);
                    sinus.setText(betasin);
                }else{
                    String betasin = Float.toString((float) Math.sin(Float.parseFloat(uhelB.getText())/ (180 / Math.PI)));
                    String betacos = Float.toString((float) Math.cos(Float.parseFloat(uhelB.getText())/ (180 / Math.PI)));
                    String betatan = Float.toString((float) Math.tan(Float.parseFloat(uhelB.getText())/ (180 / Math.PI)));
                    cosinus.setText(betacos);
                    tangen.setText(betatan);
                    sinus.setText(betasin);
                }
                if(Float.parseFloat(uhelB.getText())==30){
                    String betasin = "0.5";
                    String betacos = "√3/2";
                    String betatan = "√3/3";
                    cosinus.setText(betacos);
                    tangen.setText(betatan);
                    sinus.setText(betasin);
                }
                if(Float.parseFloat(uhelB.getText())==45){
                    String betasin = "√2/2";
                    String betacos = "√2/2";
                    String betatan = "1.0";
                    cosinus.setText(betacos);
                    tangen.setText(betatan);
                    sinus.setText(betasin);
                }
                if(Float.parseFloat(uhelB.getText())==60){
                    String betasin = "√3/2";
                    String betacos = "0.5";
                    String betatan = "√3";
                    cosinus.setText(betacos);
                    tangen.setText(betatan);
                    sinus.setText(betasin);
                }
                break;
            case 2:
                if(Float.parseFloat(uhelC.getText())==90){
                    String gamasin = "1.0";
                    String gamacos = "0.0";
                    String gamatan = "NaN";
                    cosinus.setText(gamacos);
                    tangen.setText(gamatan);
                    sinus.setText(gamasin);
                }else{
                    String gamasin = Float.toString((float) Math.sin(Float.parseFloat(uhelC.getText())/ (180 / Math.PI)));
                    String gamacos = Float.toString((float) Math.cos(Float.parseFloat(uhelC.getText())/ (180 / Math.PI)));
                    String gamatan = Float.toString((float) Math.tan(Float.parseFloat(uhelC.getText())/ (180 / Math.PI)));
                    cosinus.setText(gamacos);
                    tangen.setText(gamatan);
                    sinus.setText(gamasin);
                }
                if(Float.parseFloat(uhelC.getText())==30){
                    String gamasin = "0.5";
                    String gamacos = "√3/2";
                    String gamatan = "√3/3";
                    cosinus.setText(gamacos);
                    tangen.setText(gamatan);
                    sinus.setText(gamasin);
                }
                if(Float.parseFloat(uhelC.getText())==45){
                    String gamasin = "√2/2";
                    String gamacos = "√2/2";
                    String gamatan = "1.0";
                    cosinus.setText(gamacos);
                    tangen.setText(gamatan);
                    sinus.setText(gamasin);
                }
                if(Float.parseFloat(uhelC.getText())==60){
                    String gamasin = "√3/2";
                    String gamacos = "0.5";
                    String gamatan = "√3";
                    cosinus.setText(gamacos);
                    tangen.setText(gamatan);
                    sinus.setText(gamasin);
                }
                break;
        }
       
    }                                         

    private void VypoctiActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
       try{
        String cisloObvod = Float.toString(Float.parseFloat(stranaA.getText())+Float.parseFloat(stranaB.getText())+Float.parseFloat(stranaC.getText()));
        obvod.setText(cisloObvod);
        if(Float.parseFloat(uhelA.getText())==90||Float.parseFloat(uhelB.getText())==90||Float.parseFloat(uhelC.getText())==90){
            if(Float.parseFloat(stranaA.getText())==0){
                if(Float.parseFloat(uhelA.getText())==90){
                    String a = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)+Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaA.setText(a);
                }
                if(Float.parseFloat(uhelB.getText())==90){
                    String a = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaB.getText()),2)-Math.pow(Float.parseFloat(stranaC.getText()),2)));
                    stranaA.setText(a);
                }
                if(Float.parseFloat(uhelC.getText())==90){
                    String a = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)-Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaA.setText(a);
                }
            }
            if(Float.parseFloat(stranaB.getText())==0){
                if(Float.parseFloat(uhelB.getText())==90){
                    String b = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)+Math.pow(Float.parseFloat(stranaA.getText()),2)));
                    stranaB.setText(b);
                }
                if(Float.parseFloat(uhelA.getText())==90){
                    String b = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaA.getText()),2)-Math.pow(Float.parseFloat(stranaC.getText()),2)));
                    stranaB.setText(b);
                }
                if(Float.parseFloat(uhelC.getText())==90){
                    String b = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)-Math.pow(Float.parseFloat(stranaA.getText()),2)));
                    stranaB.setText(b);
                }
            }
            if(Float.parseFloat(stranaC.getText())==0){
                if(Float.parseFloat(uhelC.getText())==90){
                    String c = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaA.getText()),2)+Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaC.setText(c);
                }
                if(Float.parseFloat(uhelB.getText())==90){
                    String c = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaB.getText()),2)-Math.pow(Float.parseFloat(stranaA.getText()),2)));
                    stranaC.setText(c);
                }
                if(Float.parseFloat(uhelA.getText())==90){
                    String c = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaA.getText()),2)-Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaC.setText(c);
                }
            }
            
            
            if(Float.parseFloat(uhelA.getText())==90){
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/A.png")));
                String cisloObsah = Float.toString((Float.parseFloat(stranaB.getText())*Float.parseFloat(stranaC.getText()))/2);
                obsah.setText(cisloObsah);
            }
            if(Float.parseFloat(uhelB.getText())==90){
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/B.png")));
                String cisloObsah = Float.toString((Float.parseFloat(stranaA.getText())*Float.parseFloat(stranaC.getText()))/2);
                obsah.setText(cisloObsah);
            }            
            if(Float.parseFloat(uhelC.getText())==90){
                jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/C.png")));
                String cisloObsah = Float.toString((Float.parseFloat(stranaB.getText())*Float.parseFloat(stranaA.getText()))/2);
                obsah.setText(cisloObsah);
            }
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Neplatné zadání!", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
    }                                       

    private void dopoctiActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        try{
            if(Float.parseFloat(uhelA.getText())==0){
                if(Float.parseFloat(uhelB.getText())==90||Float.parseFloat(uhelC.getText())==90){  
              String alf = "45";
              uhelA.setText(alf);
              }else{
                String alf = Float.toString(180-(Float.parseFloat(uhelB.getText())+Float.parseFloat(uhelC.getText())));
            uhelA.setText(alf);}
            }
            if(Float.parseFloat(uhelB.getText())==0){
              if(Float.parseFloat(uhelA.getText())==90||Float.parseFloat(uhelC.getText())==90){  
              String bet = "45";
              uhelB.setText(bet);
              }else{
            String bet = Float.toString(180-(Float.parseFloat(uhelA.getText())+Float.parseFloat(uhelC.getText())));
            uhelB.setText(bet);}
            }  
            if(Float.parseFloat(uhelC.getText())==0){
                if(Float.parseFloat(uhelA.getText())==90||Float.parseFloat(uhelB.getText())==90){  
              String gam = "45";
              uhelC.setText(gam);
              }else{
            String gam = Float.toString(180-(Float.parseFloat(uhelB.getText())+Float.parseFloat(uhelA.getText())));
            uhelC.setText(gam);}
            }  
        if(Float.parseFloat(uhelA.getText())!=0||Float.parseFloat(uhelB.getText())!=0||Float.parseFloat(uhelC.getText())!=0){
            if(Float.parseFloat(uhelA.getText())+Float.parseFloat(uhelB.getText())+Float.parseFloat(uhelC.getText())!=180)
            JOptionPane.showMessageDialog(null, "Podle zadaných úhlů se nejedná o trojúhelník!", "Chyba", JOptionPane.ERROR_MESSAGE);}
        } catch(NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null, "Neplatné zadání!", "Chyba", JOptionPane.ERROR_MESSAGE);
        }
    }                                       

    private void dopocti_stranyActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        try{    
        if(Float.parseFloat(uhelA.getText())==90||Float.parseFloat(uhelB.getText())==90||Float.parseFloat(uhelC.getText())==90){
            if(Float.parseFloat(stranaA.getText())==0){
                if(Float.parseFloat(uhelA.getText())==90){
                    String a = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)+Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaA.setText(a);
                }
                if(Float.parseFloat(uhelB.getText())==90){
                    String a = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaB.getText()),2)-Math.pow(Float.parseFloat(stranaC.getText()),2)));
                    stranaA.setText(a);
                }
                if(Float.parseFloat(uhelC.getText())==90){
                    String a = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)-Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaA.setText(a);
                }
            }
            if(Float.parseFloat(stranaB.getText())==0){
                if(Float.parseFloat(uhelB.getText())==90){
                    String b = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)+Math.pow(Float.parseFloat(stranaA.getText()),2)));
                    stranaB.setText(b);
                }
                if(Float.parseFloat(uhelA.getText())==90){
                    String b = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaA.getText()),2)-Math.pow(Float.parseFloat(stranaC.getText()),2)));
                    stranaB.setText(b);
                }
                if(Float.parseFloat(uhelC.getText())==90){
                    String b = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaC.getText()),2)-Math.pow(Float.parseFloat(stranaA.getText()),2)));
                    stranaB.setText(b);
                }
            }
            if(Float.parseFloat(stranaC.getText())==0){
                if(Float.parseFloat(uhelC.getText())==90){
                    String c = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaA.getText()),2)+Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaC.setText(c);
                }
                if(Float.parseFloat(uhelB.getText())==90){
                    String c = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaB.getText()),2)-Math.pow(Float.parseFloat(stranaA.getText()),2)));
                    stranaC.setText(c);
                }
                if(Float.parseFloat(uhelA.getText())==90){
                    String c = Float.toString((float) Math.sqrt(Math.pow(Float.parseFloat(stranaA.getText()),2)-Math.pow(Float.parseFloat(stranaB.getText()),2)));
                    stranaC.setText(c);
                }
            }
        }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Neplatné zadání!", "Chyba", JOptionPane.ERROR_MESSAGE);
        }                                         
    }                                              

    private void jLabel9AncestorAdded(javax.swing.event.AncestorEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        try{
            String res = "0";
            stranaA.setText(res);
            stranaB.setText(res);
            stranaC.setText(res);
            uhelA.setText(res);
            uhelB.setText(res);
            uhelC.setText(res);
            obsah.setText(res);
            obvod.setText(res);
            sinus.setText(res);
            cosinus.setText(res);
            tangen.setText(res);
        }catch(Exception e){
            
        }       
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Vypocti;
    private javax.swing.JTextPane cosinus;
    private javax.swing.JButton dopocti;
    private javax.swing.JButton dopocti_strany;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane obsah;
    private javax.swing.JTextPane obvod;
    private javax.swing.JButton reset;
    private javax.swing.JTextPane sinus;
    private javax.swing.JTextPane stranaA;
    private javax.swing.JTextPane stranaB;
    private javax.swing.JTextPane stranaC;
    private javax.swing.JTextPane tangen;
    private javax.swing.JTextPane uhelA;
    private javax.swing.JTextPane uhelB;
    private javax.swing.JTextPane uhelC;
    private javax.swing.JComboBox vyberUhlu;
    // End of variables declaration                   
}
